### ISSUE TITLE
Often .git/index.lock without visible reason

### ISSUE THREAD

**Issue by chivorotkiv** [olipo186/Github-Gitlab-Auto-Deploy#23]
Hi.

I often get the following error:

    fatal: Unable to create '/project/.git/index.lock': File exists.

    If no other git process is currently running, this probably means a
    git process crashed in this repository earlier. Make sure no other git
    process is running and remove the file manually to continue.
    Pull result: 128

And I don't see any reason of that. Even if previous time I get successful pull and deploy then next time it can fail again.

My solution was check exit code and to try several times if it fails. And added 5 sec pause between tries. Like: 

```python
if self.pull(path, branch) == 0 or self.pull(path, branch) == 0 or \
   self.pull(path, branch) == 0 or self.pull(path, branch) == 0:
    self.deploy(path)
else:
    print "Error ..."
```
Two times are often enough. Four times are always enough.

1. Could you suppose a reason of `.git/indexlock` failure?
2. Do you know a better solution?
3. If I fix by this way in my branch is it worth to merge it to your repository?

Regards, Sergei.

**Comment by chivorotkiv** [comment]
@olipo186 

In this [pull request](https://github.com/olipo186/Github-Gitlab-Auto-Deploy/pull/25) I tried to solve the problem. Also I've added protection of frequent or simultaneous pushes.

**Comment by olipo186** [comment]
Great work chivorotkiv!

My guess is that git doesn't exit properly for some reason, leaving the repository locked. Maybe instances of git are still running in the background, as the error message suggests.
