### ISSUE TITLE
python error while running the script

### ISSUE THREAD

**Issue by federicovezzoli** [olipo186/Github-Gitlab-Auto-Deploy#29]
when i'm trying to run the script I get this error

File "GitAutoDeploy.py", line 65
    finally:
          ^
SyntaxError: invalid syntax

any thought? I don't know anything about python, looked the script but can't figure it out.
Could be a version problem?

thanks a lot

**Comment by alexandernst** [comment]
You need, at least, Python 2.5.x.

**Comment by federicovezzoli** [comment]
thanks
