### ISSUE TITLE
server not pulling

### ISSUE THREAD

**Issue by federicovezzoli** [olipo186/Github-Gitlab-Auto-Deploy#31]
I've set up the server and started it as a daemon when I do a pull I see this output on the daemon:

    ec2-52-28-30-194.eu-central-1.compute.amazonaws.com - - [17/Aug/2015 09:40:49] "POST / HTTP/1.1" 200 -

but no pull il happening.
the repo is always the same on the server.

any thought?

thanks

**Comment by alexandernst** [comment]
Try running the script manually and placing a few `prints` so you can check what is running and what not.

**Comment by federicovezzoli** [comment]
Sorry, I suck really bad at python.

I'm running the script by starting it as a daemon, how can I start it manually? the debug variable is set to true but nothing happens on the output.

**Comment by federicovezzoli** [comment]
it was an error on the config, the url was different, one https and one git.
